version: '3.8'

services:
  app:
    build: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - MONGODB_DATABASE_PATH=mongodb://mongodb:27017/drip
      - PORT=3001
      - IP_ADRESS=http://localhost:3001
    depends_on:
      - mongodb
    volumes:
      - ./uploads:/app/uploads
      - ./src:/app/src
      - ./.env:/app/.env
    command: npm run dev

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: 
