version: '3.8'

services:
  app:
    build: .
    ports:
      - "3002:3000"
    env_file:
      - .env
    depends_on:
      - mongodb
    volumes:
      - ./uploads:/app/uploads
      - ./src:/app/src
      - ./.env:/app/.env
    command: npm run dev

  mongodb:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
